CREATE SCHEMA SIS2402; -- Criando DB

USE SIS2402; -- SELECIONANDO DB PARA USO

CREATE TABLE SIS2402.CLIENTS
	ID_CLIENT INT NOT NULL AUTO_INCREMENT,
	NAME MEDIUMTEXT NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    BORN DATE NOT NULL,
    GENDER VARCHAR(9) NOT NULL,
    CEP INT NOT NULL,
    STREET LONGTEXT NOT NULL,
    NUMBER INT NOT NULL,
    NEIGHBORHOOD TEXT NOT NULL,
    CITY MEDIUMTEXT NOT NULL,
    UF VARCHAR(2) NOT NULL,
    COUNTRY TEXT NOT NULL,    
	PRIMARY KEY(ID_CLIENT)
);

INSERT INTO SIS2402.CLIENTS (NAME, EMAIL, BORN, GENDER, CEP, STREET, NUMBER, NEIGHBORHOOD, CITY, UF, COUNTRY)
VALUES('Guilherme Schweitzer', 'guilhermeschweitzer5@gmail.com', '23-01-2005', 'Masculino', '80500700', 'Rua Marlene Weber Saint', '106', 'Santo', 'Videira', 'SC', 'Brasil');

SELECT * FROM SIS2402.CLIENTES;